name: node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [9.4]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: apt-get install imagemagick graphicsmagick
    - run: npm install
    - run: npm run prod_build --if-present
    - run: npm test
      env:
        CI: true
